language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - "7"
before_script:
  - npm prune
script:
  - npm run build
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
